### ISSUE TITLE
support for NME?

### ISSUE THREAD

**Issue by hyusetiawan** [massiveinteractive/MassiveUnit#10]
I can't figure out how to run this to test a haxenme project? (which uses hxcpp)

on an unrelated note:
for some reason I am testing for AS2, AS3 and javascript, even though in my test.hxml, I have this:
# Flash 9+

-main TestMain
-lib munit
-lib hamcrest
-cp src

-cp test
-swf-version 9
-swf build/as3_test.swf
--next
# JavaScript

-main TestMain
-lib munit
-lib hamcrest
-cp src

-cp test
-js build/js_test.js

--next
# Neko

-main TestMain
-lib munit
-lib hamcrest
-cp src

-cp test
-neko build/neko_test.n

**Comment by Type1J** [comment]
Any progress here? I've been trying to add MUnit tests to an OpenFL project, and I was trying to find if there is any direct support for OpenFL projects, or do I still have to do the workarounds?

**Comment by joshtynjala** [comment]
I got things mostly up and running in an OpenFL library that I'm working on by copying what @jgranick is doing in the main OpenFL repository, but it would be great to see official OpenFL support that doesn't require any hacks.
