### ISSUE TITLE
Unable to run tests

### ISSUE THREAD

**Issue by RudolfVonKrugstein** [massiveinteractive/MassiveUnit#100]
From the documentation, I assumed that I can create and run an example test like this:

```
> haxelib run munit create ExampleTest
> haxelib run munit gen
> haxelib run munit test -cpp
```

The test is created (and I see the function marked with @Test), but the output of the last command suggests, that there is no test run:

```
Tests: 0  Passed: 0  Failed: 0 Errors: 0 Ignored: 0 Time: 5e-05
```

I am using haxe 3.2.0 on ubuntu 15.04.

**Comment by thomasuster** [comment]
Looks like something is up with your gen command. As it's not parsing the @Test.

```
cd ExampleTest
haxelib run munit gen
haxelib run munit test -cpp
```
The gen command should change this file.
ExampleTest/test/TestSuite.hx

Do you see anything in that file?

**Comment by RudolfVonKrugstein** [comment]
Well, after I ran

```
haxelib run munit config
```

The example test is created, and it works fine.

Now I add another test:

```
haxelib run munit create MoreTests
haxelib run munit gen
```

But the TestSuite.hx still looks like this:

```
import massive.munit.TestSuite;

import ExampleTest;

/**
 * Auto generated Test Suite for MassiveUnit.
 * Refer to munit command line tool for more information (haxelib run munit)
 */

class TestSuite extends massive.munit.TestSuite
{		

	public function new()
	{
		super();

		add(ExampleTest);
	}
}
```

**Comment by thomasuster** [comment]
Ah ha, there's your problem. You only ever run
```
haxelib run munit create 
```
One time for a project. To make another test, just copy and paste ExampleTest and change the name to AnotherTest.

Then run the gen command again.
```
haxelib run munit gen
```
This will adfd both tests to TestSuite.

Then run em!
```
haxelib run munit test -cpp
```

**Comment by RudolfVonKrugstein** [comment]
Thx

**Comment by RudolfVonKrugstein** [comment]
Oh ... But for another reason. Could it be that the Name oft the test classes must Ende in "Test"

**Comment by thomasuster** [comment]
Oh yea this is probably required. All of my test classes do.
