### ISSUE TITLE
Assert.throws and Assert.doesNotThrow

### ISSUE THREAD

**Issue by ashes999** [massiveinteractive/MassiveUnit#113]
Two methods I find useful in the .NET world are `Assert.throws(type:Dynamic, code:Void->Void)` and `Assert.doesNotThrow(code:Void->Void)`. (The latter is more for readability than actually asserting anything.)

Haxe doesn't have typed exceptions per-se (the docs suggest throwing strings), so it's easy enough to write analogues for these two methods.

Which I have done, [here](https://github.com/ashes999/build-radius/blob/master/test/AssertMore.hx). This is a quick-and-dirty version (and doesn't have type-checking for `Assert.throws`), but it's still useful for me.

I'm considering opening a PR to add these in to munit's `Assert.hx`. What do you think?

**Comment by thomasuster** [comment]
Seems a nice little function to have to me. I do the manual try catch blocks sometimes.

**Comment by ashes999** [comment]
Okay. I'll clean it up and submit a PR.

**Comment by thomasuster** [comment]
@ashes999  Cool, I can't approve PR's fyi.

**Comment by ashes999** [comment]
Derp!

I'll wait for @mikestead to take a look. 

I use these methods very, very frequently in .NET when writing unit/integration tests. I'm surprised they're not already in MUnit.

**Comment by mikestead** [comment]
Thanks for the request @ashes999.

I'm not sure I understand the `doesNotThrow` as you could simply call the function in a `@Test` and if it throws the test fails, just like any function you test.

The `throws` one makes sense. If you want to contribute `Assert.throws` please do. Remember though that in Haxe you can throw a string value or instances of a class so it would need to support the expectation of either. Also your param that takes a function you currently enforce one with no parameters which is a little restrictive. Although overly open, perhaps this should be dynamic too?

If you do get time to open a pull request please include tests to cover these scenarios.

**Comment by ashes999** [comment]
`doesNotThrow` is functionally the same as  test with no assertions. But, it communicates to the reader that "this test (or this specific block of code) often/can throw, but doesn't in this scenario." That's mostly useful as a communication tool.

The point of the parameter was to communicate "this code throws a type of X." As long as `throws` returns the exception thrown, the user can add their own checks for this later if they wish.

I'll take a look and see if I can submit a PR for `throws` which:
- Includes tests
- Allows throwing a string value
- Allows throwing an instance of a class

**Comment by ashes999** [comment]
I've submitted a PR. I'll close this issue for now. (Feel free to reopen it if you want to use it as a means of discussing the PR @mikestead)
