### ISSUE TITLE
trace() only prints first argument

### ISSUE THREAD

**Issue by Gama11** [massiveinteractive/MassiveUnit#114]
Example:

``` haxe
trace("Hello", "World");
```

Shows as:

![](http://i.imgur.com/TB1k4y5.png)

The expected behavior with Haxe's default trace implementation is to allow multiple arguments and `join` them with a comma (so the output should be `Hello,World`), see [here](http://try.haxe.org/#4a7DB).

**Comment by joshtynjala** [comment]
Ran into this one today too. It'll be hard to rewire my brain to remember that I can't pass multiple arguments to trace().

**Comment by SlavaRa** [comment]
it's bug
