### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by ashes999** [massiveinteractive/MassiveUnit#118]
Hi,

The last release was 2.1.2 in 2015. I have since added `Assert.throws`, which I need for my own code.

Is there a rough timeline for when the next release to `haxelib` will be?

I would like to switch over from using the latest git version.

**Comment by ashes999** [comment]
I'm still waiting (hoping) to get #117 into a version of MUnit I can manage with Haxelib.

@mikestead any plans for a release? It's been over a year since the last one.

**Comment by fnaith** [comment]
I am waiting next release too. Btw, it seems munit still accept PR(SlavaRa https://github.com/SlavaRa/MUnit2017).

I guess they will make next release, if available :)

**Comment by elsassph** [comment]
I'm looking into that.

**Comment by elsassph** [comment]
2.2.1 released

**Comment by fnaith** [comment]
sweeeeet
