### ISSUE TITLE
Test runner keeps being regenerated every time tests are run

### ISSUE THREAD

**Issue by benwaah** [massiveinteractive/MassiveUnit#119]
Hi, I have a very annoying issue using Munit. My test runner keeps being regenerated everytime I run my tests, whether I use the test option or the run one. The result is no test being run at all.

I'm using Munit version 2.1.2. Any help is appreciated

**Comment by elsassph** [comment]
What files are regenerated? The TestSuite for instance is always updated before running.

**Comment by benwaah** [comment]
Yes, I'm talking about the TestSuite.

I added a stub test class using `haxelib run munit create path.ClassnameTests` beforehand but the TestSuite generated does not contain anything else but the super call in new (no add())

I'm now thinking I might be missing something here. For instance, is there a convention to follow for test classes name?
Also, the .munit file only contains basic information set when `haxelib run munit config`. How is the TestRunner generated? Is there a macro here browsing the test folder for classes?

**Comment by benwaah** [comment]
OK, I found on the wiki that test classes should always end with Test.hx. I will test this right now...

**Comment by benwaah** [comment]
OK, this is it! Maybe the munit build tool could display an error message, or at least a warning, when user attempts at adding a test class which an unexpected ending :)

**Comment by elsassph** [comment]
You're right it may be a bit confusing, we should indicate that more prominently. But I don't see how we could show an error as by definition minor doesn't look for other classes...

**Comment by benwaah** [comment]
I was talking about when using the `create` option of the build tool, i.e. if user tries to do:

`munit create path.SomeClassTestName`

with SomeClassTestName not ending with Test, then it should throw an error telling the user what king of name is expected.

But I do believe that mentionning this on the home page of the wiki (section *MUnit Testing framework*) would already be a nice improvement.

**Comment by elsassph** [comment]
Oh right good idea! Can you raise that as a separate issue?

**Comment by benwaah** [comment]
Done here: [#120](https://github.com/massiveinteractive/MassiveUnit/issues/120)
