### ISSUE TITLE
junit test reports missing after upgrading to 0.9.2.1

### ISSUE THREAD

**Issue by Simn** [massiveinteractive/MassiveUnit#13]
Executing
    haxelib run munit test
does not seem to produce junit outputs in report directory anymore. report/test only contains a results.txt file with the content
   END

After downgrading to 0.9.1.2 (via haxelib set) output works again. Using haxe 2.08 on Windows 7.

**Comment by haysclark** [comment]
Wouldn't this feature be more consistent if one needed to run:

```munit report junit```
