### ISSUE TITLE
munit not working on HashLink target

### ISSUE THREAD

**Issue by sebthom** [massiveinteractive/MassiveUnit#131]
Can you please have a look at https://github.com/HaxeFoundation/hashlink/issues/52

I cannot determine whether this is a problem in HL or munit.

Thanks.

**Comment by ncannasse** [comment]
This shows an invalid MUnit behavior, which is passing the first argument of the Reflect.callMethod with an object value that does not match the function closure.

I think in that case, activeHelper.beforeClass being a closure, it should either pass the class instance on which it comes from (, or null (but that would break on non-closure platforms such as JS)

**Comment by elsassph** [comment]
@ncannasse what do you think about the PR for HL support? Apparently there's an issue in `haxe.Http` for HL's implementation.

**Comment by sebthom** [comment]
Thanks!

**Comment by elsassph** [comment]
@sebthom please give it a try
