### ISSUE TITLE
HTTPClient broken for Flash in 2.2.1

### ISSUE THREAD

**Issue by Gama11** [massiveinteractive/MassiveUnit#151]
Flash support seems to be broken in 2.2.1. When creating a fresh project with `haxelib run munit config` (confirming everything with enter) and running `haxe test.hxml`, I get the following error:

>C:\HaxeToolkit\haxe\lib\munit/2,2,1/massive/munit/client/HTTPClient.hx:256: characters 20-34 : Type not found : flash.LoadVars

@SlavaRa

**Comment by jgranick** [comment]
It was broken by this commit:

https://github.com/massiveinteractive/MassiveUnit/commit/adad6f212a5da3c1aa4603e2b8fcf40f4f9c927b#diff-f98ed25f69e97ef0d27c407840c7cae3

It removed flash9 code in favor of old flash8 code instead

**Comment by SlavaRa** [comment]
I'll fix it today

**Comment by Aurel300** [comment]
Any status on this?

**Comment by elsassph** [comment]
Sorry, I forgot about it - here's a PR:
https://github.com/massiveinteractive/MassiveUnit/pull/153

**Comment by Aurel300** [comment]
If that was for me @elsassph, no browser – I just stumbled upon this when working on Flixel's unit tests.

**Comment by elsassph** [comment]
Ah yes that's another problem then: you should specify the targets you want to test so you don't compile for Flash.
