### ISSUE TITLE
Error running munit

### ISSUE THREAD

**Issue by darmie** [massiveinteractive/MassiveUnit#172]
I just installed git version of munit, but I am getting this error:

`Error: Error parsing haxelib.json for munit@git [file_contents,/usr/local/lib/haxe/lib/munit/git/haxelib.json]`

Haxe version is 4.0.0-rc.2

**Comment by darmie** [comment]
I fixed the above error by building munit.

But I have a new error:
```
Uncaught exception - Invalid field access : get_name
```

**Comment by elsassph** [comment]
Sounds like your haxelib git wasn't pointing on the right folder.

haxelib has an undocumented extra parameter to set dev into a subfolder of the repo:
```
haxelib git [project-name] [git-clone-path] [branch] [folder]
```
You need to add `src` to the command.

What potentially fixed you issue by building is that the build script sets the dev location of munit. Aside from that you error is a bit odd :/ Looks like a Reflection error.
