### ISSUE TITLE
[OpenFL] Including lib calls Main ctor twice. Html5 target.

### ISSUE THREAD

**Issue by haxecoder** [massiveinteractive/MassiveUnit#177]
Issue is reproduced with empty openfl project html5 target. Other targets not have been investigated.
lime: [7.5.0]
mconsole: [1.6.0]
mcover: [2.2.1]
mlib: [2.0.3]
munit: [2.3.4]
openfl: [8.9.1]

haxe 4.0.0 rc3

Same behaviour within cl or ide build. 

![image](https://user-images.githubusercontent.com/2890041/67937296-62c68680-fbde-11e9-9e74-0d74a16c75ab.png)

Once library is excluded (commented) no additional call obsereved.

[AsyncTest.zip](https://github.com/massiveinteractive/MassiveUnit/files/3793174/AsyncTest.zip)

**Comment by elsassph** [comment]
I've tried your test and indeed I see this log. The compiled JS files have minor differences which don't make much sense to me.

Munit and its dependencies don't do anything themselves - they don't add any compilation parameters or automatic macros.

As OpenFl apparently uses munit for its tests, there may have some conditional behaviour when the library is referenced. You should probably raise it in the OpenFl project.
