### ISSUE TITLE
Local results server appeared to hang

### ISSUE THREAD

**Issue by bablukid** [massiveinteractive/MassiveUnit#63]
I ran into the "nekotools server" issue while running the openfl unit tests.
You already described this bug here : https://github.com/massiveinteractive/MassiveUnit/wiki/Known-Issues#http-post-causes-nekotools-server-to-hang

We finally succeeded after removing the call to sys.io.Process('nekotools') and launching nekotools-server in a parent level bash script 

    #!/bin/bash -x
    pwd=$(pwd)
    cd /cygdrive/c/projects/munit/src
    nekotools server &
    SERVER_PID=$!
    cd $pwd

    haxelib run munit test

    kill -15 $SERVER_PID    

Don't ask me why it works in this case ! Calling the server from io.Process may imply a different context of execution ... :/

**Comment by mikestead** [comment]
Fixed by #105
