### ISSUE TITLE
Support for Java and C# targets

### ISSUE THREAD

**Issue by skylerparr** [massiveinteractive/MassiveUnit#71]
With Java and C# being viable targets it would be nice to have them integrated into the test suite.

Great job on this btw.  I use this test framework every day :-)

**Comment by micahbolen** [comment]
Any progress on this?  I'm using Haxe specifically to develop an Android application, so I assume that testing with Java as the target for the munit compiler would be ideal in this situation.

**Comment by SlavaRa** [comment]
Fixed via #140 and #124
