### ISSUE TITLE
browser is required

### ISSUE THREAD

**Issue by mithepner** [massiveinteractive/MassiveUnit#85]
I'd like to be able to run munit tests automatically on the command line.  I only need the junit xml results.  This doesn't seem possible with the current options.

**Comment by jamiltron** [comment]
I also do not want munit to open a browser - how can we prevent this?

**Comment by NoxHarmonium** [comment]
Although my application targets flash and javascript which require browsers, I extracted out the code that wasn't dependant on flash or js and run tests on them using the neko target which doesn't require the browser. For example

    haxelib run munit t -neko -result-exit-code
