### ISSUE TITLE
haxe test.hxml compilation issues

### ISSUE THREAD

**Issue by as3boyan** [massiveinteractive/MassiveUnit#91]
/usr/lib/haxe/lib/munit/2,1,0/massive/munit/client/PrintClientBase.hx:349: characters 4-16 : Class<js.Lib> has no field alert
/usr/lib/haxe/lib/munit/2,1,0/massive/munit/client/PrintClient.hx:143: characters 3-15 : Class<js.Lib> has no field alert

**Comment by SlavaRa** [comment]
@elsassph this issue can be closed
